name: pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # ここで build/ の中身と index.html の先頭を出力して可視化
      - name: Show build dir
        run: |
          echo "=== ls -la build ==="
          ls -la build
          echo "=== first 80 lines of build/index.html ==="
          head -n 80 build/index.html || true

      # 重要：サブパスずれの保険。/assets/... が残っていたら /prc-arm-pose/assets/... に強制置換
      - name: Ensure subpath (/prc-arm-pose/) in index.html
        run: |
          if grep -q 'src="/assets/' build/index.html || grep -q 'href="/assets/' build/index.html; then
            sed -i 's|src="/assets/|src="/prc-arm-pose/assets/|g; s|href="/assets/|href="/prc-arm-pose/assets/|g' build/index.html
            echo "Fixed absolute asset paths in index.html"
          fi

      # base: './' を使ったり、他の要因で / が残る場合の最後の保険（必要なければそのまま）
      - name: Ensure relative fallback (optional)
        if: ${{ false }} # 必要になったら true に変更
        run: |
          sed -i 's|src="/|src="./|g; s|href="/|href="./|g' build/index.html

      - name: Add .nojekyll
        run: touch build/.nojekyll

      - name: Upload artifact (ONLY build/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
